# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jim Junker
email: james.junker1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   I am an ecologist with interests in the dynamics of ecosystem and food webs. 
   Much of my work takes place in aquatic ecosystems--from arctic streams and rivers to subtropical estuaries
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jimjunker1.github.io" 
twitter_username: jimjunker
github_username:  jimjunker1

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
