---
layout: home
limit: 10
show_excerpts: true
entries_layout: list
output:
   md_document:
    preserve_yaml: TRUE
    variant: markdown_strict
---

# Biography

I am an ecologist with broad interests in the dynamics of communities
and ecosystems. My feet are usually wet. I am interested in how
energy and elements move through ecological networks and the processes that modify energy and element flows across space and time. We take multiple approaches to address these questions including combinations of mesocosm to ecosystem-level experiments, field collections, meta-analyses, and modeling. 

Open and reproducible practices are the cornerstones of my research process. Read more of our scientific practices and values here.

I am currently a Research Assistant Professor in the Department of Biological Sciences at the [University of North Texas](https://www.unt.edu/). Please [reach out](https://biology.unt.edu/people/james-junker) if you have any questions or are interest in working together. 

## Current positions

**There are currently no specific positions open in the lab. I am open to develop projects with potential graduate or postdoctoral researchers, if research interests align. Please send me an email to discuss possible opportunities.**

## Education

* PhD Montana State University. 2019

* MS Montana State University. 2011

* BS Northland College. 2007
