---
layout: page
title: "Publications"
output: github_document
permalink: /publications/
# bibliography: pubs.bib
# csl: ecology-by-date.csl
# nocite: '@*'
---

This list is updated occasionally, however, it may be missing the most hot-off-the-press items. I also maintain [scholar](https://scholar.google.com/citations?user=q3E1S9MAAAAJ&hl=en) and [OrcID](<https://orcid.org/0000-0001-9713-2330>) pages, check these for the most updated list.

<!-- <!--- ## -->
<!-- ```{r get pubs, echo=FALSE, message=FALSE, warning=FALSE} -->

<!-- source("./publications/get_pubs.R") -->

<!-- ``` -->
<!-- -->

## preprints

Gjoni, V., J. P. F. Pomeranz, ***J. R. Junker***, and J. S. Wesner. (2024). *Size spectra in freshwater streams are consistent across temperature and resource supply*. bioRxiv. [LINK](https://doi.org/10.1101/2024.01.09.574822).

## accepted/in press

## 2024

***Junker, J. R.***, W. F. Cross, J. M. Hood, J. P. Benstead, A. D. Huryn, D. Nelson, J. S. Ólafsson, and G. M. Gíslason. (2024). *Environmental warming increases the importance of high-turnover energy channels in stream food webs*. Ecology 105:e4314. DOI:<!--- --->10.1002/ecy.4314. [PDF](./pdfs/Junker et al. - 2024 - Environmental warmin increases the importance of.pdf). [LINK](https://onlinelibrary.wiley.com/doi/abs/10.1002/ecy.4314).

Pomeranz, J., ***J. R. Junker***, V. Gjoni, and J. S. Wesner. (2024). *Maximum likelihood outperforms binning methods for detecting differences in abundance size spectra across environmental gradients*. Journal of Animal Ecology 93:267–280.DOI:<!--- --->10.1111/1365-2656.14044. [PDF](./pdfs/Pomeranz et al. - 2024 - Maximum likelihood outperforms binning methods for.pdf). [LINK](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.14044).

Wesner, J. S., J. P. F. Pomeranz, ***J. R. Junker***, and V. Gjoni. (2024). *Bayesian hierarchical modelling of size spectra*. Methods in Ecology and Evolution 15:856–867. DOI:<!--- --->10.1111/2041-210X.14312. [PDF](./pdfs/Wesner et al. - 2024 - Bayesian hierarchical modelling of size spectra.pdf). [LINK](https://onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.14312).

## 2023

Scholl, E. A., W. F. Cross, C. S. Guy, A. J. Dutton, and ***J. R. Junker***. (2023). *Landscape diversity promotes stable food-web architectures in large rivers*. Ecology Letters 26:1740–1751. DOI:<!--- --->10.1111/ele.14289. [PDF](./pdfs/Scholl et al. - 2023 - Landscape diversity promotes stable food-web archi.pdf). [LINK](https://onlinelibrary.wiley.com/doi/abs/10.1111/ele.14289)

Keppeler, F. W., ***J. R. Junker***, M. J. Shaw, S. B. Alford, A. S. Engel, L. M. Hooper-Bùi, O. P. Jensen, K. Lamb, P. C. López-Duarte, C. W. Martin, A. M. McDonald, J. A. Olin, A. T. Paterson, M. J. Polito, N. N. Rabalais, B. J. Roberts, R. E. Rossi, and E. M. Swenson. (2023). *Can biodiversity of preexisting and created salt marshes match across scales? An assessment from microbes to predators*. Ecosphere 14:e4461. DOI:<!-- -->10.1002/ecs2.4461.[PDF](./pdfs/Keppeler et al. - 2023 - Can biodiversity of preexisting and created salt m.pdf). [Link](https://onlinelibrary.wiley.com/doi/abs/10.1002/ecs2.4461)

## 2022

* Pomeranz, J. P. F., ***J. R. Junker***, & J. S. Wesner. (2022). *Individual size distributions across North America vary with local temperature*. Global Change Biology 28(3): 848-858. DOI:<!-- -->10.1111/gcb.15862. [PDF](./pdfs/Pomeranz et al. - 2022 - Individual size distributions across North America.pdf). Editor invited commentary [LINK](https://doi.org/10.1111/gcb.15981).

* Reinert, J. H., ***J. R. Junker***, & L. K. Albertson. (2022). *Influence of biomimicry structures on ecosystem function in a Rocky Mountain incised stream*. Ecosphere 13(1):e3897. DOI:<!-- -->10.1002/ecs2.3897. [LINK](https://doi.org/10.1002/ECS2.3897)

## 2021

* ***Junker, J. R.***, W. F. Cross, J. P. Benstead, A. D. Huryn, J. M. Hood, D. Nelson, G. M. G&iacute;slason, & J. S. &Oacute;lafsson. (2021). *Flow is more important that temperature in driving patterns of organic matter storage and stoichiometry in stream ecosystems*. Ecosystems 24(6):1317-1331. DOI:<!-- -->10.1007/s10021-020-00585-6. [PDF](./pdfs/Junker et al. - 2020 - Flow is more Important than Temperature in Driving.pdf)

* Scholl, E. A., W. F. Cross, J. R. Junker, M. J. MacDonald, J. A. Sanchez-Ruiz, B. B. Tumolo, & M. R. Whiles. (2021). *Are human remediation efforts responsible for increases in insect abundance?*. [PDF](./pdfs/Scholl et al. - 2021 - Are human remediation efforts responsible for increases in insect abundance.pdf) [LINK](https://www.science.org/do/10.1126/comment.746993/full/). Technical comment on [van Klink et al. in *Science*](https://www.science.org/doi/abs/10.1126/science.aax9931). 

## 2020

* ***Junker, J. R.***, W. F. Cross, J. P. Benstead, A. D. Huryn, J. M. Hood, D. Nelson, G. M. G&iacute;slason, & J. S. &Oacute;lafsson. (2020). *Resource supply governs the apparent temperature dependence of animal production in stream ecosystems*. Ecology Letters 23(12):1809-1819. DOI:<!-- -->10.1111/ele.13608. [PDF](./pdfs/Junker et al. - 2020 - Resource supply governs the apparent temperature d.pdf)

* Nelson, D., J. P. Benstead, A. D. Huryn, W. F. Cross, J. M. Hood, P. W. Johnson, ***J. R. Junker***, G. M. G&iacute;slason, & J. S. &Oacute;lafsson. (2020). *Contrasting responses of black fly species (Diptera: Simuliidae) to experimental whole-stream warming*. Freshwater Biology 65(10):1793-1805.DOI:<!-- -->10.1111/fwb.13583. [PDF](https://par.nsf.gov/servlets/purl/10228694)

* Nelson, D., J. P. Benstead, A. D. Huryn, W. F. Cross, J. M. Hood, P. W. Johnson, ***J. R. Junker***, G. M. G&iacute;slason, & J. S. &Oacute;lafsson. (2020). *Thermal niche diversity and trophic redundancy drive neutral effects of warming on energy flux through a stream food web*. Ecology 101(4):e02952.DOI:<!-- -->10.1002/ecy.2952. [LINK](https://esajournals.onlinelibrary.wiley.com/doi/am-pdf/10.1002/ecy.2952)

* W. F. Cross, K. A. Henderson, ***J. R. Junker***, & E. A. Scholl. (2020). *Secondary Production*. Oxford Bibliographies. *Oxford University Press*. [DOI:10.1093/obo/9780199830060-0231](https://www.oxfordbibliographies.com/view/document/obo-9780199830060/obo-9780199830060-0231.xml)

## 2019

* J. D'Andrilli, ***J. R. Junker***, H. J. Smith, E. A. Scholl & C. M. Foreman. (2019). *DOM composition alters ecosystem function during microbial processing of isolated sources*. Biogeochemistry 142(2):281-298. DOI:<!-- -->10.1007/s10533-018-00534-5. [LINK](https://link.springer.com/article/10.1007/s10533-018-00534-5)

## 2018

* Hood, J. M., J. P. Benstead, W. F. Cross, A. D. Huryn, P. W. Johnson, G. M. G&iacute;slason, ***J. R. Junker***, D. Nelson, J. S. &Oacute;lafsson, & C. Tran. (2018). *Increased resource use efficiency amplifies positive response of aquatic primary production to experimental warming*. Global Change Biology 24(3):1069-1084. DOI:<!-- -->10.1111/gcb.13912. [PDF](./pdfs/hood_et_al-2018-global_change_biology.pdf)

## 2017

* Nelson, D., J. P. Benstead, A. D. Huryn, W. F. Cross, J. M. Hood, P. W. Johnson, ***J. R. Junker***, G. M. G&iacute;slason, & J. S. &Oacute;lafsson. (2017). *Experimental whole-stream warming alters community size structure*. Global Change Biology 23(7):2618-2628. DOI:<!-- -->10.1111/gcb.13574. [PDF](./pdfs/nelson_et_al-2016-global_change_biology.pdf)

* Nelson, D., J. P. Benstead, A. D. Huryn, W. F. Cross, J. M. Hood, P. W. Johnson, ***J. R. Junker***, G. M. G&iacute;slason, & J. S. &Oacute;lafsson. (2017). *Shifts in community size structure drive temperature invariance of secondary production in a stream-warming experiment*. Ecology 98(7):1797-1806. DOI:<!-- -->10.1002/ecy.1857. [PDF](./pdfs/nelson_et_al-2017-ecology-2.pdf)

## 2014

* ***Junker, J. R.*** & W. F. Cross. (2014). *Seasonality in the trophic basis of a temperate stream invertebrate assemblage: Importance of temperature and food quality*. Limnology and Oceanography 59(2):507-518. DOI:<!-- -->10.4319/lo.2014.59.2.0507. [PDF](./pdfs/Junker and Cross - 2014 - Seasonality in the trophic basis of a temperate st.pdf)

## 2012

* O'Gorman, E. J.,...,***J. R. Junker***,..., & G. Woodward (30 authors). (2012). *Impacts of warming on the structure and functioning of aquatic communities: individual- to ecosystem-level responses*. Advances in ecological research 47:81-176. DOI:<!-- -->10.1016/B978-0-12-398315-2.00002-8. [LINK](https://www.zora.uzh.ch/id/eprint/88276/1/O%27Gorman2012Zora.pdf)